name: Create Release Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 19
      uses: actions/setup-java@v4
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: maven
        
    - name: Build the JAR with Maven
      run: ./mvnw -B clean package --file pom.xml
      
    - name: Create custom JRE with jlink
      run: |
        jlink --module-path $JAVA_HOME/jmods \
              --add-modules java.base,java.logging,java.sql,java.desktop \
              --output custom-jre \
              --compress=2 \
              --no-header-files \
              --no-man-pages
      
    - name: Prepare Release Package
      run: |
        mkdir release-package
        cp target/SyntaxN.jar release-package/
        cp run.bat release-package/
        cp run.sh release-package/
        cp -r webpage release-package/
        cp -r custom-jre release-package/jre   
        
    - name: Create Versioned ZIP Archive
      run: |
        cd release-package
        zip -r ../SyntaxN-${{ github.ref_name }}.zip .
        
    - name: Upload to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./SyntaxN-${{ github.ref_name }}.zip
        asset_name: SyntaxN-${{ github.ref_name }}.zip
        asset_content_type: application/zip
